pkg/npu_pkg.sv
common/reset_bridge.sv
control/ctrl_regs.sv
control/pmu.sv
control/instr_queue.sv
control/fetch_unit.sv
control/dep_tracker.sv
control/dma_lane.sv
control/compute_lane.sv
control/instr_sequencer.sv
control/stream_buffer_adapter.sv
control/dma_unit.sv
control/activate_unit.sv
memory/bram_sdp.sv
memory/imem.sv
memory/weight_buffer.sv
memory/activation_buffer.sv
memory/bias_buffer.sv
memory/out_buffer.sv
memory/quant_buffer.sv
pe/pe.sv
systolic_array/systolic_array.sv
top/npu_core.sv
