SIM = verilator
HW_DIR?=$(shell cd ../../.. && pwd)
RTL_DIR?=$(HW_DIR)/rtl
VERILOG_SOURCES += $(RTL_DIR)/pkg/npu_pkg.sv \
                  $(RTL_DIR)/pe/mac_unit.sv

TOPLEVEL = mac_unit
MODULE = mac_unit_tb

include $(shell cocotb-config --makefiles)/Makefile.sim
